# $FreeBSD$

SUBDIR=		acpi_acer_amw0 acpi_acer_wmid acpi_asus acpi_asus_wmi \
		acpi_fujitsu acpi_hp acpi_ibm acpi_panasonic acpi_sony \
		acpi_toshiba acpi_video acpi_dock acpi_wmi aibs

.include <bsd.subdir.mk>
